spring.application.name=backend-j

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/backendj
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=backend-j-super-secret-key-must-be-at-least-256-bits-long!
jwt.expiration-ms=86400000

backend.p.url=http://localhost:8000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
